### ISSUE TITLE
Dashboard dropdown displayed under the top bar

### ISSUE THREAD

**Issue by lmartins** [ryansommers/slate#2]
There's a z-index issue with the dropdown of the Dashboard menu being displayed under the top bar:

![screenshot 2014-12-08 22 36 09](https://cloud.githubusercontent.com/assets/151981/5348789/bcac5cc8-7f2a-11e4-898c-dbd84e1591ca.png)

**Comment by ryansommers** [comment]
This was fixed in 1.1.1
