### ISSUE TITLE
status update message layout seems off

### ISSUE THREAD

**Issue by leo-cheron** [ryansommers/slate#4]
Hi, 

Status update message gets over the side bar on WordPress 4.3.1.

![screen shot 2015-11-15 at 17 30 06](https://cloud.githubusercontent.com/assets/418965/11169677/9610b64e-8bbe-11e5-82f7-5938f85305dc.png)

Regards

**Comment by pimdoenders** [comment]
-- Please reply above this line --

Hi Ryansommers/slate We have received your email. We will respond to
you as soon as possible.Kind regards!

---

## Ryansommers/slate sent a message, on Nov 15 @ 17:31 (CET):

```
Hi, 

Status update message gets over the side bar on WordPress 4.3.1. 

 [1] 

Regards 

-
```

 Reply to this email directly or view it on GitHub [2].

## Links:

[1]
https://cloud.githubusercontent.com/assets/418965/11169677/9610b64e-8bbe-11e5-82f7-5938f85305dc.png
[2] https://github.com/ryansommers/slate/issues/4

---
